/* tslint:disable */
require("./CateringPage.module.css");
const styles = {
  title: 'title_ec2afdca',
  sub: 'sub_ec2afdca',
  sectionTitle: 'sectionTitle_ec2afdca',
  panel: 'panel_ec2afdca',
  tileGrid: 'tileGrid_ec2afdca',
  tile: 'tile_ec2afdca',
  tileBig: 'tileBig_ec2afdca',
  tileIcon: 'tileIcon_ec2afdca',
  tileIconBig: 'tileIconBig_ec2afdca',
  tableWrap: 'tableWrap_ec2afdca',
  table: 'table_ec2afdca',
  rowTitle: 'rowTitle_ec2afdca',
  tableEmpty: 'tableEmpty_ec2afdca',
  tableFooter: 'tableFooter_ec2afdca',
  sidebarLayout: 'sidebarLayout_ec2afdca',
  sidebarFilter: 'sidebarFilter_ec2afdca',
  filterHeading: 'filterHeading_ec2afdca',
  filterActive: 'filterActive_ec2afdca',
  filterBar: 'filterBar_ec2afdca',
  viewToggle: 'viewToggle_ec2afdca',
  toggleActive: 'toggleActive_ec2afdca',
  faqTabs: 'faqTabs_ec2afdca',
  faqTab: 'faqTab_ec2afdca',
  faqTabActive: 'faqTabActive_ec2afdca',
  faqItem: 'faqItem_ec2afdca',
  faqQuestion: 'faqQuestion_ec2afdca',
  faqAnswer: 'faqAnswer_ec2afdca',
  searchWrap: 'searchWrap_ec2afdca',
  pageHeaderRow: 'pageHeaderRow_ec2afdca',
  body: 'body_ec2afdca',
  partnerPanel: 'partnerPanel_ec2afdca',
  partnerLogos: 'partnerLogos_ec2afdca',
  benefitRow: 'benefitRow_ec2afdca',
  menuGrid: 'menuGrid_ec2afdca',
  menuCard: 'menuCard_ec2afdca',
  menuHeader: 'menuHeader_ec2afdca',
  menuPhoto: 'menuPhoto_ec2afdca',
  lunchPanel: 'lunchPanel_ec2afdca',
  lunchHeader: 'lunchHeader_ec2afdca',
  lunchPhoto: 'lunchPhoto_ec2afdca',
  lunchColumns: 'lunchColumns_ec2afdca',
  orderRow: 'orderRow_ec2afdca',
  orderSteps: 'orderSteps_ec2afdca',
  assistPanel: 'assistPanel_ec2afdca'
};

export default styles;
/* tslint:enable */